import { defaultResumeData } from "./types/resume";
export const resumeExamples = [
  { id: "software", role: "Software Engineer", industry: "Technology", summary: "Software engineer focused on dependable web applications, accessible interfaces, and clear collaboration with product teams.", skills: ["TypeScript", "React", "SQL", "Testing"], bullets: ["Built an accessible account settings interface with validation and keyboard navigation.", "Added regression tests for checkout failures and documented recovery steps."], advice: "Name the systems you built, their users, and verified improvements in reliability or speed." },
  { id: "marketing", role: "Digital Marketing Manager", industry: "Marketing", summary: "Digital marketing professional experienced in campaign planning, audience analysis, and translating performance data into practical optimizations.", skills: ["Campaign strategy", "Analytics", "Google Ads", "Budget management"], bullets: ["Coordinated campaign launches across paid search and social with creative and analytics teams.", "Built a weekly performance report connecting campaign spending to qualified leads."], advice: "Include real budgets, conversion results, attribution context, and the channels you managed." },
  { id: "data", role: "Data Analyst", industry: "Technology", summary: "Data analyst who turns operational data into clear reports and actionable recommendations for business teams.", skills: ["SQL", "Python", "Power BI", "Data quality"], bullets: ["Created a dashboard that helped operations teams identify delayed orders.", "Validated source records and documented recurring data quality issues."], advice: "Describe the decision your analysis supported and how you checked data accuracy." },
  { id: "nurse", role: "Registered Nurse", industry: "Healthcare", summary: "Nursing professional experienced in patient assessment, care coordination, and accurate clinical documentation.", skills: ["Patient assessment", "Care coordination", "Clinical documentation", "Patient education"], bullets: ["Coordinated patient handovers with multidisciplinary teams using structured documentation.", "Provided discharge education to patients and caregivers following approved care plans."], advice: "Include your actual license, clinical setting, and relevant certifications. Omit patient-identifying information." },
  { id: "finance", role: "Financial Analyst", industry: "Finance", summary: "Financial analyst experienced in budget reporting, variance analysis, and preparing clear financial explanations for business partners.", skills: ["Financial modeling", "Excel", "Budgeting", "Variance analysis"], bullets: ["Prepared monthly budget variance reports and reviewed assumptions with department leads.", "Reconciled reporting inputs and documented the financial close process."], advice: "Quantify portfolio scope or forecasting improvements only when you can substantiate them." },
  { id: "sales", role: "Account Executive", industry: "Sales", summary: "Sales professional focused on understanding customer needs, managing opportunities, and building lasting client relationships.", skills: ["Discovery", "CRM", "Negotiation", "Account planning"], bullets: ["Managed customer opportunities from discovery through proposal and handover.", "Partnered with product specialists to address customer requirements during demonstrations."], advice: "Use your actual quota attainment, sales cycle, deal size, or retention figures." },
  { id: "teacher", role: "Teacher", industry: "Education", summary: "Educator experienced in lesson planning, differentiated instruction, and helping learners build confidence through clear feedback.", skills: ["Lesson planning", "Assessment", "Classroom management", "Differentiated instruction"], bullets: ["Adapted lesson activities to different learning needs using formative assessments.", "Collaborated with families and colleagues to support individual learning goals."], advice: "Specify the subjects, age groups, qualifications, and evidence of learning progress." },
  { id: "graduate", role: "Graduate / First Job", industry: "Early career", summary: "Recent graduate with hands-on project experience, strong research habits, and an interest in applying classroom learning to practical problems.", skills: ["Research", "Communication", "Project coordination", "Problem solving"], bullets: ["Coordinated a student project, assigned responsibilities, and presented findings to faculty.", "Reviewed source material and documented methods so teammates could reproduce the analysis."], advice: "Replace sample experience with your internships, volunteering, or academic projects. Put relevant education near the top." },
] as const;

export function exampleResume(id: string) {
  const example = resumeExamples.find(e => e.id === id);
  if (!example) return null;
  return { ...defaultResumeData, name: `${example.role} — practice draft`, contact: { ...defaultResumeData.contact, jobTitle: example.role }, summary: `<p>${example.summary}</p>`,
    experience: [{ id: crypto.randomUUID(), company: "Replace with your employer or project", position: example.role, startDate: "", endDate: "", current: false, location: "", description: `<ul>${example.bullets.map(b => `<li>${b}</li>`).join("")}</ul>` }],
    skills: example.skills.map(name => ({ id: crypto.randomUUID(), name, level: "" })),
  };
}
